[[valid]]
filename = "ce#1.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#1.sam >ce#1.bam"]

[[valid]]
filename = "ce#2.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#2.sam >ce#2.bam"]

[[valid]]
filename = "ce#5.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#5.sam >ce#5.bam"]

[[valid]]
filename = "ce#5b.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#5b.sam >ce#5b.bam"]

[[valid]]
filename = "ce#unmap.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#unmap.sam >ce#unmap.bam"]

[[valid]]
filename = "ce#unmap1.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#unmap1.sam >ce#unmap1.bam"]

[[valid]]
filename = "ce#unmap2.bam"
origin = "htslib"
comments = ["samtools view -b ../SAM/ce#unmap2.sam >ce#unmap2.bam"]

[[valid]]
filename = "bam1.bam"
origin = "BioPython"

[[valid]]
filename = "bam2.bam"
origin = "BioPython"

[[valid]]
filename = "ex1.bam"
origin = "BioPython"

[[valid]]
filename = "ex1_header.bam"
origin = "BioPython"

[[valid]]
filename = "GSE25840_GSM424320_GM06985_gencode_spliced.head.bam"
origin = "Gene Expression Omnibus"
tags = ["bai"]
comments = ["the first 10,000 lines were extracted using samtools"]

[[valid]]
filename = "R_12h_D06.uniq.q40.bam"
origin = "in-house"
tags = ["bai"]
comments = ["empty", "BAI"]

[[valid]]
filename = "cigar-64k.bam"
origin = "Heng-Li"
tags = ["bai"]
comments = ["records with long-cigar strings (>65535 operations)"]
